src/kinya/urls.py
from django.conf.urls.defaults import *
import lessons.views
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    #(r'^kinya/', include('kinya.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     (r'^admin/', include(admin.site.urls)),
     
     # our lessons
     (r'^$', lessons.views.quiz),

     # ajax call for lessons
     (r'^ajax/get_lessons$', lessons.views.ajax_lessons),

     # static files
     (r'^static/(?P<path>.*)$', 'django.views.static.serve',
      {'document_root': settings.MEDIA_ROOT}),
)

src/kinya/lessons/models.py
from django.db import models
from django.contrib.auth.models import User

class Lesson(models.Model):
    name = models.CharField(max_length=64)
    lesson = models.TextField()
    slug = models.SlugField()
    number = models.IntegerField()
    owner = models.ForeignKey(User)
    created = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    def __unicode__(self):
        return self.name

class Question(models.Model):
    lesson = models.ForeignKey(Lesson)
    question = models.CharField(max_length=255)
    answer = models.CharField(max_length=255)
    truth = models.CharField(max_length=255)
    note = models.CharField(max_length=255, null=True, blank=True)
    audio = models.FileField(upload_to="audio", null=True, blank=True)

    def __unicode__(self):
        return "%s - %s" % (self.question, self.answer)
    
class Attendance(models.Model):
    user = models.ForeignKey(User)
    lesson = models.ForeignKey(Lesson)
    active = models.BooleanField(default=True)
    started = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return "%s - %s" % (self.lesson.name, self.started)
    
class Record(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    right = models.IntegerField(default=0)
    wrong = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    last = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return "%s - +%d -%d" % (self.question.question, self.right, self.wrong)

src/kinya/lessons/views.py
from django.shortcuts import render_to_response
from .models import Lesson, Question

def lessons(request):
    lessons = Lesson.objects.filter(active=True).order_by('number')
    return render_to_response('lessons/lessons.html', { 'lessons': lessons })

def quiz(request):
    return render_to_response('lessons/quiz.html');

def ajax_lessons(request):
    lessons = Lesson.objects.filter(active=True).order_by('number')
    return render_to_response('lessons/ajax_lessons.html', { 'lessons': lessons })

templates/base.html
<html>

<head>
<title>{% block title %}Kinya{% endblock %}</title>
</head>

<body>
{% block body %}ze body{% endblock %}
</body>

</html>

templates/lessons/ajax_lessons.html
[
{% for lesson in lessons %}
{ "name": "{{ lesson.name }}",
  "pk": {{ lesson.pk }},
  "enabled": true,
  "questions": [
  {% for question in lesson.question_set.all %}
    { "q": "{{ question.question|safe }}", "t": "{{ question.truth|safe }}", "a": "{{ question.answer|safe }}", "n": "{{ question.note|safe }}", "pk": {{ question.pk }}, "s": 0,  "m": 0, "dq": 0, "aud": "{{ question.audio }}" }
    {% if not forloop.last %},{% endif %}
  {% endfor %}
  ]
}
{% if not forloop.last %},{% endif %}
{% endfor %}
]

templates/lessons/lessons.html
{% extends 'base.html' %}

{% block body %}
{% for lesson in lessons %}
<div class="lesson">
	<h2>{{ lesson.number }} - {{ lesson.name }}</h2>
</div>
{% endfor %}
{% endblock %}

templates/lessons/quiz.html
<html>

<head>
<link type="text/css" rel="stylesheet" href="/static/style.css" />
<script type="text/javascript" src="/static/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="/static/scripts.js"></script>
</head>

<body>

<div id="current">

<div id="quiz_question"></div>
<div id="quiz_note"></div>
<input id="quiz_answer" type="textfield" size="30" autocomplete="off" /><br/>

<div id="quiz_correction">
  <div id="quiz_right_answer"></div>
  <div id="quiz_continue">
  press enter to continue
  </div>
</div>

<div id="difficulty_queues">
  <div id="learning">learning</div>
  <div id="mastered">mastered</div>
  <div id="dq0">
  </div>
  <div id="dq1">
  </div>
  <div id="dq2">
  </div>
  <div id="dq3">
  </div>
</div>

</div>

<div id="right">

<div id="upcoming">
</div>

<div id="lessons">
</div>

</div>

<div id="quiz_right">
</div>

<div id="quiz_wrong">
</div>

<div id="error">
</div>

</body>

</html>